export enum ChitType {
  FIXED_DRAW = 'FIXED_DRAW',
  AUCTION = 'AUCTION',
}
export enum ChitStatus {
  DRAFT = 'DRAFT',
  INVITING = 'INVITING',
  MEMBERS_CONFIRMED = 'MEMBERS_CONFIRMED',
  READY_TO_START = 'READY_TO_START',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
}
export enum ChitMonthType {
  ACTION = 'ACTION',
  AGENT_CHIT = 'AGENT_CHIT',
}
export enum ChitMonthStatus {
  SCHEDULED = 'SCHEDULED',
  COLLECTION = 'COLLECTION',
  VERIFICATION = 'VERIFICATION',
  READY_FOR_ACTION = 'READY_FOR_ACTION',
  ACTION_IN_PROGRESS = 'ACTION_IN_PROGRESS',
  SETTLEMENT = 'SETTLEMENT',
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
}
export enum ParticipationRole {
  PARTICIPANT = 'PARTICIPANT',
  CO_ORGANIZER = 'CO_ORGANIZER',
}
export enum ParticipantStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXIT_REQUESTED = 'EXIT_REQUESTED',
  EXITED = 'EXITED',
  REMOVED = 'REMOVED',
}
export enum PaymentMethod {
  UPI = 'UPI',
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  OTHER = 'OTHER',
}
export enum PaymentStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  PARTIAL = 'PARTIAL',
  OVERDUE = 'OVERDUE',
  WAIVED = 'WAIVED',
  DISPUTED = 'DISPUTED',
}
export enum DrawStatus { SCHEDULED='SCHEDULED', READY='READY', IN_PROGRESS='IN_PROGRESS', COMPLETED='COMPLETED', CANCELLED='CANCELLED', DISPUTED='DISPUTED' }
export enum DrawSelectionMethod { RANDOM='RANDOM', MANUAL='MANUAL' }
export enum AuctionStatus { SCHEDULED='SCHEDULED', READY='READY', LIVE='LIVE', CLOSING='CLOSING', CLOSED='CLOSED', SETTLED='SETTLED', CANCELLED='CANCELLED', DISPUTED='DISPUTED' }
export enum AuctionMode { LIVE_VISIBLE='LIVE_VISIBLE', SEALED='SEALED', MANUAL='MANUAL' }
export enum BidStatus { VALID='VALID', INVALID='INVALID', WITHDRAWN='WITHDRAWN', WINNING='WINNING', NON_WINNING='NON_WINNING' }
export enum PayoutStatus { PENDING='PENDING', PROCESSING='PROCESSING', PAID='PAID', FAILED='FAILED', DISPUTED='DISPUTED', CANCELLED='CANCELLED' }
export enum EligibilityStatus { ELIGIBLE='ELIGIBLE', INELIGIBLE='INELIGIBLE', SUSPENDED='SUSPENDED', DEFAULTED='DEFAULTED', ALREADY_WON='ALREADY_WON' }
export enum LedgerEntryType {
  CONTRIBUTION_DUE='CONTRIBUTION_DUE',
  CONTRIBUTION_PAYMENT='CONTRIBUTION_PAYMENT',
  CONTRIBUTION_ADJUSTMENT='CONTRIBUTION_ADJUSTMENT',
  AGENT_CHIT_COLLECTION='AGENT_CHIT_COLLECTION',
  AGENT_SETTLEMENT='AGENT_SETTLEMENT',
  DRAW_PAYOUT='DRAW_PAYOUT',
  AUCTION_GROSS_POOL='AUCTION_GROSS_POOL',
  AUCTION_DISCOUNT='AUCTION_DISCOUNT',
  AUCTION_PAYOUT='AUCTION_PAYOUT',
  LATE_FEE='LATE_FEE',
  REFUND='REFUND',
  ADJUSTMENT='ADJUSTMENT',
  OTHER='OTHER',
}
