import React,{useCallback,useEffect,useState}from'react';import{Alert,ScrollView,Text,View}from'react-native';import{router,useLocalSearchParams}from'expo-router';import{chitsApi,agentApi,dashboardApi,usersApi}from'@/src/api/all';import{Badge,Button,Card,Loading,Screen,Stat,s}from'@/src/components/UI';import{useAuth}from'@/src/state/Auth';import{isAdmin,isCreator,isAgent,isMember,canOperate}from'@/src/state/roles';import{money,date,errMsg}from'@/src/lib/format';
export default function ChitDetail(){
 const{chitId}=useLocalSearchParams<{chitId:string}>();const{user}=useAuth();const[chit,setChit]=useState<any>();const[access,setAccess]=useState<any>();const[dash,setDash]=useState<any>();const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!chitId)return;try{const r=await chitsApi.get(String(chitId));const d=r.data?.data??r.data;setChit(d);try{const x=await dashboardApi.chit(String(chitId));setDash(x.data?.data??x.data)}catch{}if(isAgent(user)&&!isCreator(user,d)){try{const x=await agentApi.chit(String(chitId));setAccess(x.data?.data??x.data)}catch{setAccess(undefined)}}}catch(e){Alert.alert('Unable to load',errMsg(e))}},[chitId,user?.id]);
 useEffect(()=>{load()},[load]);if(!chit)return <Screen title="Chit" back={()=>router.back()}><Loading/></Screen>;
 const status=String(chit.status||'').toUpperCase();const creator=isCreator(user,chit);const manage=canOperate(user,chit,'can_manage_chit',access);const verify=canOperate(user,chit,'can_verify_payments',access);const collect=canOperate(user,chit,'can_collect_cash',access);const canSetup=creator||isAdmin(user)||manage;const editableStatus=['DRAFT','INVITING','MEMBERS_CONFIRMED'].includes(status);const months=Array.isArray(chit.months)?chit.months:[];const firstOpen=months.find((m:any)=>!['LOCKED','COMPLETED'].includes(String(m.status||'').toUpperCase()));
 const start=async()=>{setBusy(true);try{const r=await chitsApi.start(String(chit.id));const d=r.data?.data??r.data;Alert.alert('Chit started',`The chit is active. First open month: ${String(d.startedMonth??firstOpen?.month_number??'—')}.`);await load()}catch(e){Alert.alert('Start failed',errMsg(e))}finally{setBusy(false)}};
 const deleteDraft=async()=>{Alert.alert('Delete draft?','This permanently removes this unstarted draft. It cannot be used for operations.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await usersApi.deleteChit(String(chit.id));Alert.alert('Deleted','Draft chit deleted.');router.back()}catch(e){Alert.alert('Delete failed',errMsg(e))}}}])};
 return <Screen title={String(chit.name||'Chit')} subtitle={`${String(chit.chit_type||'')} · ${status}`} back={()=>router.back()}><ScrollView>
  <View style={s.row}><Stat label="Face" value={money(chit.total_chit_amount)}/><Stat label="Savings" value={money(chit.currentSavings??chit.accumulated_savings_amount)}/></View><View style={s.row}><Stat label="Members" value={chit.total_members}/><Stat label="Progress" value={`${chit.completed_months||0}/${chit.total_months}`}/></View>
  {canSetup&&editableStatus&&<Card><Text style={s.section}>{status==='DRAFT'?'Complete setup and publish':'Chit setup'}</Text><Text style={s.muted}>Review the monthly schedule and publish only after the required members and agent configuration are complete.</Text><Button title={status==='DRAFT'?'Setup & Publish Chit':'Setup / Publish Chit'} onPress={()=>router.push({pathname:'/chit-setup',params:{chitId:String(chit.id)}})}/></Card>}
  {status==='DRAFT'&&isAdmin(user)&&<Button title="Delete Draft Chit" danger onPress={deleteDraft} disabled={busy}/>} 
  {status==='READY_TO_START'&&<Card><Text style={s.section}>Published — Ready to Start</Text><Text style={s.muted}>Configuration is locked. Start the chit to enable the first open month.</Text><Button title="Start Chit" onPress={start} disabled={busy}/></Card>}
  {status==='ACTIVE'&&<Card><Text style={s.section}>Chit Active</Text><Text style={s.muted}>The first open month is the current operational month. Completed and locked months are read-only.</Text></Card>}
  <Card><Text style={s.section}>Financial plan</Text><Text>Current savings: {money(chit.currentSavings??chit.accumulated_savings_amount)}</Text><Text style={s.muted}>Every active member contributes the scheduled amount. Payouts are settled only after the required verified funds are available.</Text></Card>
  {Boolean(dash?.financial)&&<Card><Text style={s.section}>Dashboard</Text><Text>Collected: {money(dash.financial.collected)}</Text><Text>Settled payouts: {money(dash.financial.settled_payouts)}</Text><Text>Outstanding: {money(dash.financial.outstanding)}</Text></Card>}
  <Card><Text style={s.section}>Monthly schedule</Text>{months.map((m:any)=>{const monthStatus=String(m.status||'').toUpperCase();const active=!['LOCKED','COMPLETED'].includes(monthStatus);const current=Boolean(firstOpen&&String(firstOpen.id)===String(m.id));const action=String(m.month_type||'ACTION').toUpperCase()==='ACTION';const canOpenAction=status==='ACTIVE'&&current&&active&&action;const canOpenAgent=status==='ACTIVE'&&current&&active&&String(m.month_type).toUpperCase()==='AGENT_CHIT'&&(creator||isAdmin(user)||manage);const canPay=status==='ACTIVE'&&current&&active;
    return <Card key={String(m.id)}><View style={s.row}><View style={{flex:1}}><Text style={{fontWeight:'800'}}>Month {String(m.month_number)}{current?' · CURRENT':''}</Text><Text style={s.muted}>{date(m.scheduled_date)} · {money(m.scheduled_amount)} / member</Text><Text style={s.muted}>{String(m.month_type).toUpperCase()==='AGENT_CHIT'?'Agent month — no draw/bid':`Action month — ${String(chit.chit_type).toUpperCase()==='AUCTION'?'auction':'fixed draw'}`}</Text></View><Badge tone={monthStatus==='COMPLETED'||monthStatus==='LOCKED'?'green':'orange'}>{monthStatus||'UNKNOWN'}</Badge></View><Text>Payout: {money(m.winner_payout_amount)}</Text>
      {canOpenAction&&String(chit.chit_type).toUpperCase()==='FIXED_DRAW'&&<Button title={isMember(user)?'View / Interest in Fixed Draw':'Open / Manage Fixed Draw'} secondary onPress={()=>router.push({pathname:'/fixed-draw',params:{chitId:String(chit.id),monthId:String(m.id)}})}/>} 
      {canOpenAction&&String(chit.chit_type).toUpperCase()==='AUCTION'&&<Button title={isMember(user)?'View / Bid in Auction':'Open / Manage Auction'} secondary onPress={()=>router.push({pathname:'/auction',params:{chitId:String(chit.id),monthId:String(m.id)}})}/>} 
      {canOpenAgent&&<Button title="Agent Month / Settlement" secondary onPress={()=>router.push({pathname:'/agent-month',params:{chitId:String(chit.id),monthId:String(m.id)}})}/>} 
      {canPay&&<Button title={isMember(user)?'Pay Contribution / Payments':'Contribution / Payments'} secondary onPress={()=>router.push({pathname:'/payment',params:{chitId:String(chit.id),monthId:String(m.id)}})}/>} 
      {(manage||isAdmin(user)||creator)&&monthStatus==='COMPLETED'&&<Button title="Reconciliation" secondary onPress={()=>router.push({pathname:'/reconciliation',params:{chitId:String(chit.id),monthId:String(m.id)}})}/>} 
      {(manage||isAdmin(user)||creator)&&monthStatus==='COMPLETED'&&<Button title="Close & Lock Month" secondary onPress={()=>router.push({pathname:'/month-close',params:{monthId:String(m.id)}})}/>} 
    </Card>})}</Card>
  {manage&&<Button title="Members & Invitations" secondary onPress={()=>router.push({pathname:'/members',params:{chitId:String(chit.id)}})}/>}{verify&&<Button title="Collections / Verify Payments" secondary onPress={()=>router.push({pathname:'/collections',params:{chitId:String(chit.id)}})}/>}{collect&&<Button title="Payouts / Settlement" secondary onPress={()=>router.push({pathname:'/payouts',params:{chitId:String(chit.id)}})}/>}{(creator||isAdmin(user)||isAgent(user))&&<Button title="Ledger" secondary onPress={()=>router.push({pathname:'/ledger',params:{chitId:String(chit.id)}})}/>}{isMember(user)&&<Button title="My Ledger" secondary onPress={()=>router.push({pathname:'/ledger',params:{chitId:String(chit.id)}})}/>}{Boolean(chit.responsibleAgent)&&<Card><Text style={s.section}>Responsible agent</Text><Text>{String(chit.responsibleAgent.name||'Agent')} · {String(chit.responsibleAgent.mobile||'—')}</Text>{chit.responsibleAgent.upi_id&&<Text style={s.muted}>UPI: {String(chit.responsibleAgent.upi_id)}</Text>}</Card>} <Button title="Refresh" secondary onPress={load}/>
 </ScrollView></Screen>}
