import React,{useState}from'react';
import{Alert,ScrollView,Text,View}from'react-native';
import{router}from'expo-router';
import{chitsApi,chitImportApi,participantsApi}from'@/src/api/all';
import{Badge,Button,Card,Input,Screen,s}from'@/src/components/UI';
import{errMsg,money}from'@/src/lib/format';

type Method='CASH'|'UPI'|'BANK_TRANSFER'|'OTHER';
type Member={memberId:string;name:string;mobile?:string;upiId?:string;sequence:number};
type Payment={monthNumber:number;memberId:string;amount:string;method:Method;reference:string;notes:string};
type PayoutComponent={amount:string;method:Method;reference:string;notes:string};
type Month={monthNumber:number;amount:string;completedAt:string;winnerMemberId:string;winnerName:string;winnerMobile:string;payoutAmount:string;openingSavings:string;closingSavings:string;collectedAmount:string;discountAmount:string;winnerReference:string;notes:string;payoutComponents:PayoutComponent[]};

const blankMonth=(n:number):Month=>({monthNumber:n,amount:'',completedAt:'',winnerMemberId:'',winnerName:'',winnerMobile:'',payoutAmount:'',openingSavings:n===1?'0':'',closingSavings:'',collectedAmount:'',discountAmount:'',winnerReference:'',notes:'',payoutComponents:[]});
const blankPayment=(monthNumber:number,memberId:string):Payment=>({monthNumber,memberId,amount:'',method:'CASH',reference:'',notes:''});
const num=(v:any)=>Number(v||0);

export default function ExistingChit(){
 const[chitId,setChitId]=useState(''),[nextMonth,setNextMonth]=useState(''),[monthsCount,setMonthsCount]=useState(''),[chit,setChit]=useState<any>(),[members,setMembers]=useState<Member[]>([]),[months,setMonths]=useState<Month[]>([]),[payments,setPayments]=useState<Payment[]>([]),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[review,setReview]=useState<any>(),[batchId,setBatchId]=useState('');
 const historicalCount=Math.max(1,num(nextMonth)-1);
 const updateMonth=(i:number,k:keyof Month,v:string)=>setMonths(x=>x.map((m,j)=>j===i?{...m,[k]:v}:m));
 const updatePayment=(i:number,k:keyof Payment,v:string)=>setPayments(x=>x.map((p,j)=>j===i?{...p,[k]:v}:p));
 const updatePayout=(mi:number,pi:number,k:keyof PayoutComponent,v:string)=>setMonths(x=>x.map((m,i)=>i===mi?{...m,payoutComponents:m.payoutComponents.map((p,j)=>j===pi?{...p,[k]:v}:p)}:m));
 const loadChit=async()=>{if(!chitId.trim())return Alert.alert('Chit ID required','Enter the existing chit UUID.');setBusy(true);try{const r=await chitsApi.get(chitId.trim());const d=r.data?.data??r.data;setChit(d);const ps=await participantsApi.list(chitId.trim());const rows=ps.data?.data??ps.data;const source=Array.isArray(rows)?rows:rows?.participants||[];setMembers(source.map((x:any,i:number)=>({memberId:String(x.user_id||x.userId||x.id),name:String(x.name||x.user_name||`Member ${i+1}`),mobile:x.mobile||x.mobile_number,upiId:x.upiId||x.upi_id,sequence:Number(x.participant_sequence||x.sequence||i+1)})));setStep(2)}catch(e){Alert.alert('Unable to load chit',errMsg(e))}finally{setBusy(false)}};
 const prepareMonths=()=>{const expected=Math.max(1,num(nextMonth)-1),entered=num(monthsCount||expected);if(!num(nextMonth)||num(nextMonth)<=1)return Alert.alert('Next active month required','Enter a month number greater than 1.');if(entered!==expected)return Alert.alert('Historical month count mismatch',`Next active month ${nextMonth} requires exactly ${expected} historical month(s).`);setMonths(Array.from({length:expected},(_,i)=>blankMonth(i+1)));setPayments([]);setStep(3)};
 const validateLocal=()=>{const errors:string[]=[];const ids=new Set(members.map(x=>x.memberId));const ordered=[...months].sort((a,b)=>a.monthNumber-b.monthNumber);const expectedMonths=Math.max(1,num(nextMonth)-1);if(ordered.length!==expectedMonths)errors.push(`Enter all ${expectedMonths} historical month(s) before activation.`);ordered.forEach((m,i)=>{if(m.monthNumber!==i+1)errors.push(`Historical months must be continuous; expected month ${i+1}.`);if(!m.amount||num(m.amount)<=0)errors.push(`Month ${m.monthNumber}: contribution amount required.`);if(!m.closingSavings)errors.push(`Month ${m.monthNumber}: closing savings required.`);if(m.monthNumber!==1&&!m.openingSavings)errors.push(`Month ${m.monthNumber}: opening savings required.`);if(num(m.openingSavings)<0||num(m.closingSavings)<0)errors.push(`Month ${m.monthNumber}: savings cannot be negative.`);if(m.monthNumber>1&&Math.abs(num(m.openingSavings)-num(ordered[i-1].closingSavings))>.01)errors.push(`Month ${m.monthNumber}: opening savings must equal previous closing savings.`);const rows=payments.filter(p=>p.monthNumber===m.monthNumber);const collected=rows.reduce((a,p)=>a+num(p.amount),0);const payoutParts=m.payoutComponents.filter(p=>num(p.amount)>0).reduce((a,p)=>a+num(p.amount),0);if(m.payoutAmount&&m.payoutComponents.length&&Math.abs(payoutParts-num(m.payoutAmount))>.01)errors.push(`Month ${m.monthNumber}: payout components must equal payout amount.`);if(m.collectedAmount&&Math.abs(num(m.collectedAmount)-collected)>.01)errors.push(`Month ${m.monthNumber}: collected summary must equal collection transactions.`);if(collected>num(m.amount)*members.length+.01)errors.push(`Month ${m.monthNumber}: collections exceed scheduled member contributions.`);const calculated=num(m.openingSavings)+collected-num(m.payoutAmount);if(Math.abs(num(m.closingSavings)-calculated)>.01)errors.push(`Month ${m.monthNumber}: closing savings does not reconcile.`);});payments.forEach(p=>{if(!ids.has(p.memberId))errors.push(`Payment has unknown member ${p.memberId}.`);if(num(p.amount)<=0)errors.push(`Payment for month ${p.monthNumber} must be greater than zero.`)});return errors};
 const build=()=>({chitId:chitId.trim(),currentMonthNumber:num(nextMonth),members,months,payments});
 const validate=async()=>{const e=validateLocal();if(e.length)return Alert.alert('Review required',e.join('\n'));setBusy(true);try{const r=await chitImportApi.validate(build());const d=r.data?.data??r.data;setReview(d);if(!d.valid)Alert.alert('Validation failed',(d.errors||[]).join('\n'));else{Alert.alert('Validated','Historical data passed API validation.');setStep(5)}}catch(x){Alert.alert('Validation failed',errMsg(x))}finally{setBusy(false)}};
 const createBatch=async()=>{const e=validateLocal();if(e.length)return Alert.alert('Review required',e.join('\n'));setBusy(true);try{const r=await chitImportApi.createBatch(build());const d=r.data?.data??r.data;if(!d?.id)throw new Error(r.data?.message||'Unable to create import batch');await chitImportApi.review(String(d.id));setBatchId(String(d.id));const q=await chitImportApi.getBatch(String(d.id));setReview(q.data?.data??q.data);setStep(5)}catch(x){Alert.alert('Create batch failed',errMsg(x))}finally{setBusy(false)}};
 const apply=()=>Alert.alert('Apply historical data?','Historical months will be locked and the selected next month will become active.',[{text:'Cancel',style:'cancel'},{text:'Apply',style:'default',onPress:async()=>{setBusy(true);try{const r=await chitImportApi.apply(batchId);const d=r.data?.data??r.data;if(!r.data?.success)throw new Error(r.data?.message||'Apply failed');Alert.alert('Running chit activated',`Month ${d.currentMonthNumber||nextMonth} is now active.`);router.replace({pathname:'/chit-detail',params:{chitId:chitId.trim()}})}catch(x){Alert.alert('Apply failed',errMsg(x))}finally{setBusy(false)}}}]);
 const addPayment=(m:number,id:string)=>setPayments(x=>[...x,blankPayment(m,id)]);
 const addPayout=(mi:number)=>setMonths(x=>x.map((m,i)=>i===mi?{...m,payoutComponents:[...m.payoutComponents,{amount:'',method:'CASH',reference:'',notes:''}]}:m));
 const renderPayment=(p:Payment,real:number)=> <Card key={real}><Text style={{fontWeight:'700'}}>{members.find(x=>x.memberId===p.memberId)?.name||p.memberId}</Text><Input label="Amount" value={p.amount} onChangeText={v=>updatePayment(real,'amount',v)} keyboardType="decimal-pad"/><View style={s.row}><Button title="CASH" secondary={p.method!=='CASH'} onPress={()=>updatePayment(real,'method','CASH')}/><Button title="UPI" secondary={p.method!=='UPI'} onPress={()=>updatePayment(real,'method','UPI')}/></View><Input label="Reference" value={p.reference} onChangeText={v=>updatePayment(real,'reference',v)}/><Button title="Remove collection" secondary onPress={()=>setPayments(x=>x.filter((_,i)=>i!==real))}/></Card>;
 const renderPayout=(m:Month,mi:number,p:PayoutComponent,pi:number)=><Card key={pi}><Input label="Component amount" value={p.amount} onChangeText={v=>updatePayout(mi,pi,'amount',v)} keyboardType="decimal-pad"/><View style={s.row}><Button title="CASH" secondary={p.method!=='CASH'} onPress={()=>updatePayout(mi,pi,'method','CASH')}/><Button title="UPI" secondary={p.method!=='UPI'} onPress={()=>updatePayout(mi,pi,'method','UPI')}/></View><Input label="Reference" value={p.reference} onChangeText={v=>updatePayout(mi,pi,'reference',v)}/><Button title="Remove payout component" secondary onPress={()=>setMonths(x=>x.map((mm,j)=>j===mi?{...mm,payoutComponents:mm.payoutComponents.filter((_,k)=>k!==pi)}:mm))}/></Card>;
 const renderMonth=(m:Month,mi:number)=><Card key={m.monthNumber}><View style={s.row}><Text style={s.section}>Month {m.monthNumber}</Text><Badge tone="green">HISTORICAL</Badge></View><Input label="Contribution / member" value={m.amount} onChangeText={v=>updateMonth(mi,'amount',v)} keyboardType="decimal-pad"/><Input label="Completed date (ISO)" value={m.completedAt} onChangeText={v=>updateMonth(mi,'completedAt',v)}/><Input label="Opening savings" value={m.openingSavings} onChangeText={v=>updateMonth(mi,'openingSavings',v)} keyboardType="decimal-pad"/><Input label="Closing savings" value={m.closingSavings} onChangeText={v=>updateMonth(mi,'closingSavings',v)} keyboardType="decimal-pad"/><Input label="Collected amount (summary)" value={m.collectedAmount} onChangeText={v=>updateMonth(mi,'collectedAmount',v)} keyboardType="decimal-pad"/><Input label="Winner member ID (optional)" value={m.winnerMemberId} onChangeText={v=>updateMonth(mi,'winnerMemberId',v)}/><Input label="Winner name" value={m.winnerName} onChangeText={v=>updateMonth(mi,'winnerName',v)}/><Input label="Winner mobile" value={m.winnerMobile} onChangeText={v=>updateMonth(mi,'winnerMobile',v)} keyboardType="phone-pad"/><Input label="Payout amount" value={m.payoutAmount} onChangeText={v=>updateMonth(mi,'payoutAmount',v)} keyboardType="decimal-pad"/><Input label="Auction discount (optional)" value={m.discountAmount} onChangeText={v=>updateMonth(mi,'discountAmount',v)} keyboardType="decimal-pad"/><Input label="Winner payout reference" value={m.winnerReference} onChangeText={v=>updateMonth(mi,'winnerReference',v)}/><Text style={s.section}>Collections</Text>{payments.filter(p=>p.monthNumber===m.monthNumber).map(p=>renderPayment(p,payments.indexOf(p)))}{members.map(mem=><Button key={mem.memberId} title={`Add collection · ${mem.name}`} secondary onPress={()=>addPayment(m.monthNumber,mem.memberId)}/>)}<Text style={s.section}>Payout settlement</Text>{m.payoutComponents.map((p,pi)=>renderPayout(m,mi,p,pi))}<Button title="Add payout component" secondary onPress={()=>addPayout(mi)}/><Input label="Month notes" value={m.notes} onChangeText={v=>updateMonth(mi,'notes',v)} multiline/></Card>;
 const totalExpected=months.reduce((a,m)=>a+num(m.amount)*members.length,0),totalCollected=payments.reduce((a,p)=>a+num(p.amount),0),totalPayout=months.reduce((a,m)=>a+num(m.payoutAmount),0);
 return <Screen title="Existing / Running Chit" subtitle={`Onboarding wizard · Step ${step} of 5`} back={()=>router.back()}><ScrollView keyboardShouldPersistTaps="handled"><Card><Text style={s.section}>Step 1 · Select existing chit</Text><Input label="Existing chit ID" value={chitId} onChangeText={setChitId} placeholder="Chit UUID"/><Input label="Next active month number" value={nextMonth} onChangeText={setNextMonth} placeholder="4" keyboardType="number-pad"/><Text style={s.muted}>Historical months: {historicalCount} · Enter all completed months before activation</Text>{chit&&<Badge tone="green">{String(chit.name||'Chit')} · {String(chit.chit_type||'')}</Badge>}<Button title="Load chit & members" onPress={loadChit} disabled={busy}/></Card>{step>=2&&<Card><Text style={s.section}>Step 2 · Members</Text>{members.map(m=><Card key={m.memberId}><Text style={{fontWeight:'800'}}>{m.sequence}. {m.name}</Text><Text style={s.muted}>{m.mobile||'No mobile'}{m.upiId?` · ${m.upiId}`:''}</Text></Card>)}<Input label="Historical months to enter" value={monthsCount} onChangeText={setMonthsCount} keyboardType="number-pad"/><Button title="Enter historical months" onPress={prepareMonths} disabled={busy||!members.length}/></Card>}{step>=3&&months.map(renderMonth)}{step>=3&&<Card><Text style={s.section}>Step 4 · Financial review</Text><Text>Members: {members.length}</Text><Text>Expected historical contributions: {money(totalExpected)}</Text><Text>Entered collection transactions: {money(totalCollected)}</Text><Text>Historical payouts: {money(totalPayout)}</Text><Text style={s.muted}>Split payments use separate CASH and UPI rows; MIXED is never stored.</Text><Button title="Validate with API" onPress={validate} disabled={busy}/><Button title="Create & review import batch" secondary onPress={createBatch} disabled={busy}/></Card>}{step>=5&&<Card><Text style={s.section}>Step 5 · Final review & activation</Text><Badge tone="green">{review?.status||'VALIDATED'}</Badge>{review?.counts&&<Text>Members {review.counts.members} · Historical months {review.counts.historicalMonths} · Payments {review.counts.payments}</Text>}<Text style={s.muted}>After apply: historical months are LOCKED; Month {nextMonth} becomes active.</Text><Button title="Apply & Activate Running Chit" onPress={apply} disabled={busy||!batchId}/></Card>}</ScrollView></Screen>;
}
