import React,{useEffect,useState}from'react';import{Alert,ScrollView,Text,View}from'react-native';import{router,useLocalSearchParams}from'expo-router';import{participantsApi,chitsApi,agentApi}from'@/src/api/all';import{Button,Card,Input,Loading,Screen,s,Badge}from'@/src/components/UI';import{errMsg}from'@/src/lib/format';import{useAuth}from'@/src/state/Auth';import{isAdmin,isCreator,isAgent}from'@/src/state/roles';
export default function Members(){const{chitId}=useLocalSearchParams<{chitId:string}>();const{user}=useAuth();const[data,setData]=useState<any[]>([]);const[chit,setChit]=useState<any>();const[access,setAccess]=useState<any>();const[mobile,setMobile]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const[p,c]=await Promise.all([participantsApi.list(String(chitId)),chitsApi.get(String(chitId))]);const cd=c.data?.data??c.data;setData(p.data?.data??[]);setChit(cd);if(isAgent(user)&&!isCreator(user,cd)){try{const a=await agentApi.chit(String(chitId));setAccess(a.data?.data??a.data)}catch{setAccess(undefined)}}}catch(e){Alert.alert('Unable to load',errMsg(e))}finally{setLoading(false)}};useEffect(()=>{if(chitId)load()},[chitId]);
 const invite=async()=>{const normalized=mobile.trim().replace(/\s+/g,'');if(normalized.replace(/\D/g,'').length<10)return Alert.alert('Invalid mobile','Enter a valid 10 digit mobile number');setBusy(true);try{await participantsApi.invite(String(chitId),normalized);setMobile('');Alert.alert('Invitation sent','The user can accept it from their account.');await load()}catch(e){Alert.alert('Invite failed',errMsg(e))}finally{setBusy(false)}};
 if(loading)return <Screen title="Members" back={()=>router.back()}><Loading/></Screen>;if(!chit)return <Screen title="Members" back={()=>router.back()}><Card><Text>Chit not found.</Text><Button title="Back" secondary onPress={()=>router.back()}/></Card></Screen>;
 const canManage=isAdmin(user)||isCreator(user,chit)||(isAgent(user)&&access?.can_manage_chit===true);return <Screen title="Members" subtitle="Participants & invitations" back={()=>router.back()}><ScrollView>
 {canManage&&<Card><Text style={s.section}>Invite user</Text><Text style={s.muted}>Enter the user's mobile number. The backend sends/creates the invitation; you do not need a user or participant ID.</Text><Input label="Mobile number" value={mobile} onChangeText={setMobile} keyboardType="phone-pad" placeholder="+919999999999"/><Button title="Invite User" onPress={invite} disabled={busy}/></Card>}
 {data.length===0&&<Card><Text style={s.muted}>No participants found.</Text></Card>}
 {data.map(p=><Card key={p.id}><View style={s.row}><Text style={{fontWeight:'800',flex:1}}>{p.name||p.user_name||p.user?.name||`Member ${p.participantSequence||p.participant_sequence||''}`}</Text><Badge tone={String(p.status||p.invitation_status||'').toUpperCase().includes('ACTIVE')||String(p.invitation_status||'').toUpperCase()==='ACCEPTED'?'green':'orange'}>{p.status||p.invitation_status||'UNKNOWN'}</Badge></View><Text>{p.mobile||p.user_mobile||p.user?.mobile||'—'}</Text><Text style={s.muted}>Participant ID: {p.id}</Text></Card>)}
 </ScrollView></Screen>}
