import React,{useCallback,useEffect,useState}from'react';import{Alert,ScrollView,Text,View}from'react-native';import{router,useLocalSearchParams}from'expo-router';import{paymentsApi,chitsApi,agentApi}from'@/src/api/all';import{Badge,Button,Card,Input,Loading,Screen,s}from'@/src/components/UI';import{date,errMsg,idempotency,money}from'@/src/lib/format';import{useAuth}from'@/src/state/Auth';import{isAgent,isCreator,isMember,canOperate}from'@/src/state/roles';
export default function Payment(){const{chitId,monthId}=useLocalSearchParams<{chitId:string;monthId:string}>();const{user}=useAuth();const[data,setData]=useState<any>();const[pays,setPays]=useState<any[]>([]);const[chit,setChit]=useState<any>();const[access,setAccess]=useState<any>();const[amount,setAmount]=useState('');const[method,setMethod]=useState('UPI');const[reference,setReference]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[o,p,c]=await Promise.all([paymentsApi.obligations(String(chitId),String(monthId)),paymentsApi.list(String(chitId),String(monthId)),chitsApi.get(String(chitId))]);setData(o.data?.data??o.data);setPays(p.data?.data?.payments??p.data?.data??[]);const cd=c.data?.data??c.data;setChit(cd);if(isAgent(user)&&!isCreator(user,cd)){try{const a=await agentApi.chit(String(chitId));setAccess(a.data?.data??a.data)}catch{setAccess(undefined)}}}catch(e){Alert.alert('Unable to load',errMsg(e))}},[chitId,monthId,user?.id]);
 useEffect(()=>{if(chitId&&monthId)load()},[load]);if(!data)return <Screen title="Payments" back={()=>router.back()}><Loading/></Screen>;
 const mine=Array.isArray(data.obligations)&&data.obligations.length>0?data.obligations[0]:null;const canVerify=canOperate(user,chit,'can_verify_payments',access);const agent=chit?.responsibleAgent;const submit=async()=>{if(!mine)return Alert.alert('No obligation','Your contribution obligation is not available for this month.');const n=Number(amount||mine.outstandingAmount);if(!Number.isFinite(n)||n<=0||n>Number(mine.outstandingAmount))return Alert.alert('Invalid amount',`Outstanding amount is ${money(mine.outstandingAmount)}.`);if(!reference.trim())return Alert.alert('Reference required',method==='CASH'?'Enter a cash receipt/reference number.':'Enter the UPI/bank transaction reference.');setBusy(true);try{await paymentsApi.submit(String(chitId),String(mine.chitParticipantId),{amount:n.toFixed(2),paymentMethod:method,transactionReference:reference.trim(),paymentDate:new Date().toISOString(),obligationId:mine.id,notes:method==='CASH'?'Cash paid to responsible agent':'UPI/bank transfer recorded from mobile',idempotencyKey:idempotency()});Alert.alert('Payment submitted','Your payment is pending verification by the chit operator.');setAmount('');setReference('');await load()}catch(e){Alert.alert('Payment failed',errMsg(e))}finally{setBusy(false)}};
 const verify=async(p:any)=>{setBusy(true);try{await paymentsApi.verify(p.id,{status:'VERIFIED'});await load()}catch(e){Alert.alert('Verification failed',errMsg(e))}finally{setBusy(false)}};
 return <Screen title={`Month ${String(data.monthNumber)}`} subtitle={`${date(data.scheduledDate)} · ${money(data.scheduledAmount)} / member`} back={()=>router.back()}><ScrollView>
  <Card><Text style={s.section}>Where to pay</Text><Text style={s.muted}>Cash: hand the contribution to the responsible agent and keep the receipt/reference. UPI: transfer to the responsible agent's UPI ID and enter the transaction reference below.</Text>{agent?<><Text style={{fontWeight:'800',marginTop:10}}>Responsible agent: {String(agent.name||'Agent')}</Text><Text>{String(agent.mobile||'—')}</Text>{agent.upi_id?<Text style={s.success}>UPI ID: {String(agent.upi_id)}</Text>:<Text style={s.danger}>UPI ID is not configured. Ask the agent for the correct UPI ID before paying.</Text>}</>:<Text style={s.danger}>Responsible agent payment details are not configured yet. Contact the chit operator.</Text>}</Card>
  {mine&&<Card><Text style={s.section}>My contribution</Text><Text>Due {money(mine.dueAmount)} · Paid {money(mine.paidAmount)} · Outstanding {money(mine.outstandingAmount)}</Text><Badge tone={mine.status==='VERIFIED'?'green':'orange'}>{String(mine.status||'PENDING')}</Badge>{isMember(user)&&Number(mine.outstandingAmount)>0&&<><Input label="Amount" value={amount} onChangeText={setAmount} placeholder={String(mine.outstandingAmount)} keyboardType="decimal-pad"/><Text style={s.muted}>Payment method</Text><View style={s.row}>{['UPI','CASH','BANK_TRANSFER'].map(x=><Button key={x} title={x} secondary={method!==x} onPress={()=>setMethod(x)}/>)}</View><Input label={method==='CASH'?'Cash receipt / reference':'Transaction reference'} value={reference} onChangeText={setReference} placeholder={method==='CASH'?'CASH-001':'UPI-12345'} autoCapitalize="characters"/><Button title="Submit Contribution" onPress={submit} disabled={busy}/></>}</Card>}
  {canVerify&&<Card><Text style={s.section}>Verify member payments</Text>{pays.length===0&&<Text style={s.muted}>No submitted payments yet.</Text>}{pays.map(p=><Card key={String(p.id)}><Text style={{fontWeight:'800'}}>Member {String(p.participantSequence||p.participant_sequence||'')}</Text><Text>{money(p.amount)} · {String(p.paymentMethod||p.payment_method||'')} · {String(p.transactionReference||p.transaction_reference||'—')}</Text><Badge tone={p.status==='VERIFIED'?'green':'orange'}>{String(p.status||'UNKNOWN')}</Badge>{p.status!=='VERIFIED'&&<Button title="Verify" onPress={()=>verify(p)} disabled={busy}/>}</Card>)}</Card>}
  <Button title="Refresh" secondary onPress={load}/>
 </ScrollView></Screen>}
