import { Body, Controller, Global, Module, Post, Req, UnauthorizedException, TooManyRequestsException, ServiceUnavailableException } from '@nestjs/common';
import { ApiBearerAuth, ApiProperty, ApiTags } from '@nestjs/swagger';
import { IsString, Length } from 'class-validator';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { JwtModule, JwtService } from '@nestjs/jwt';
import { Sequelize } from 'sequelize-typescript';
import { randomBytes, randomInt, createHash, createHmac, timingSafeEqual } from 'crypto';
import { JwtAuthGuard } from './jwt-auth.guard';
import { DatabaseModule } from '../../database/database.module';

class RequestOtpDto { @ApiProperty({example:'+919999999999'}) @IsString() @Length(10,16) mobile!:string; }
class VerifyOtpDto { @ApiProperty({example:'+919999999999'}) @IsString() @Length(10,16) mobile!:string; @ApiProperty({example:'123456'}) @IsString() @Length(4,8) otp!:string; }
class RefreshDto { @ApiProperty() @IsString() @Length(32,512) refreshToken!:string; }
function normalizeMobile(value:string){return value.trim().replace(/[\s()-]/g,'');}
function hash(value:string){return createHash('sha256').update(value).digest('hex');}
function otpHash(otp:string,pepper:string){return createHmac('sha256',pepper).update(otp).digest('hex');}
function safeEqual(a:string,b:string){const aa=Buffer.from(a,'utf8'),bb=Buffer.from(b,'utf8');return aa.length===bb.length&&timingSafeEqual(aa,bb);}

@ApiTags('Authentication') @Controller({path:'auth',version:'1'})
class AuthController {
 constructor(private readonly jwt:JwtService,private readonly db:Sequelize,private readonly config:ConfigService){}
 private access(userId:string,mobile:string,roles:string[]){return this.jwt.sign({sub:userId,mobile,roles},{secret:this.config.getOrThrow('JWT_ACCESS_SECRET'),expiresIn:this.config.get('JWT_ACCESS_EXPIRES','15m')});}
 private async createRefresh(userId:string,req:any,transaction?:any){const raw=randomBytes(48).toString('base64url');const days=Number(this.config.get('JWT_REFRESH_DAYS','30'))||30;const [rows]:any=await this.db.query(`INSERT INTO refresh_sessions(id,user_id,token_hash,expires_at,user_agent,ip_address) VALUES(gen_random_uuid(),:user,:hash,NOW()+(:days || ' days')::interval,:ua,:ip) RETURNING id,expires_at`,{replacements:{user:userId,hash:hash(raw),days,ua:String(req?.headers?.['user-agent']||'').slice(0,500),ip:String(req?.ip||'').slice(0,64)},transaction});return{token:raw,id:rows[0].id,expiresAt:rows[0].expires_at};}
 @Post('request-otp') async requestOtp(@Body()d:RequestOtpDto){const mobile=normalizeMobile(d.mobile);const [recent]:any=await this.db.query(`SELECT COUNT(*)::int AS n FROM otp_challenges WHERE normalized_mobile=:mobile AND created_at>NOW()-INTERVAL '10 minutes'`,{replacements:{mobile}});if(Number(recent[0]?.n||0)>=5)throw new TooManyRequestsException('Too many OTP requests. Try again later.');const provider=this.config.get('OTP_PROVIDER','CONSOLE').toUpperCase();if(this.config.get('NODE_ENV','development')==='production'&&provider==='CONSOLE'&&this.config.get('AUTH_ALLOW_CONSOLE_OTP','false')!=='true')throw new ServiceUnavailableException('Production OTP provider is not configured');const otp=provider==='CONSOLE'?String(this.config.get('DEV_OTP','123456')):String(randomInt(100000,1000000));const ttl=Number(this.config.get('OTP_TTL_SECONDS','300'))||300;const pepper=this.config.getOrThrow('OTP_PEPPER');await this.db.query(`UPDATE otp_challenges SET consumed_at=NOW(),updated_at=NOW() WHERE normalized_mobile=:mobile AND consumed_at IS NULL`,{replacements:{mobile}});await this.db.query(`INSERT INTO otp_challenges(id,normalized_mobile,otp_hash,expires_at,max_attempts) VALUES(gen_random_uuid(),:mobile,:hash,NOW()+(:ttl || ' seconds')::interval,5)`,{replacements:{mobile,hash:otpHash(otp,pepper),ttl}});await this.deliverOtp(mobile,otp);const expose=this.config.get('AUTH_EXPOSE_OTP_IN_RESPONSE','false')==='true';return{success:true,data:{message:'OTP sent',mobile,expiresInSeconds:ttl,...(expose?{devOtp:otp}:{})}};}
 private async deliverOtp(mobile:string,otp:string){const provider=this.config.get('OTP_PROVIDER','CONSOLE').toUpperCase();if(provider==='CONSOLE')return;if(provider!=='TWILIO')throw new ServiceUnavailableException('No production OTP provider is configured');const sid=this.config.getOrThrow('TWILIO_ACCOUNT_SID'),token=this.config.getOrThrow('TWILIO_AUTH_TOKEN'),from=this.config.getOrThrow('TWILIO_FROM');const body=new URLSearchParams({To:mobile,From:from,Body:`Your Chit verification code is ${otp}. It expires soon.`});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new ServiceUnavailableException('OTP delivery failed');}
 @Post('verify-otp') async verify(@Body()d:VerifyOtpDto,@Req()req:any){const mobile=normalizeMobile(d.mobile),pepper=this.config.getOrThrow('OTP_PEPPER');const [rows]:any=await this.db.query(`SELECT * FROM otp_challenges WHERE normalized_mobile=:mobile AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1`,{replacements:{mobile}});if(!rows.length)throw new UnauthorizedException('OTP challenge not found or already used');const c=rows[0];if(new Date(c.expires_at).getTime()<=Date.now())throw new UnauthorizedException('OTP expired');if(Number(c.attempts)>=Number(c.max_attempts))throw new UnauthorizedException('OTP attempt limit exceeded');await this.db.query(`UPDATE otp_challenges SET attempts=attempts+1,updated_at=NOW() WHERE id=:id`,{replacements:{id:c.id}});if(!safeEqual(c.otp_hash,otpHash(d.otp,pepper)))throw new UnauthorizedException('Invalid OTP');await this.db.query(`UPDATE otp_challenges SET consumed_at=NOW(),updated_at=NOW() WHERE id=:id`,{replacements:{id:c.id}});const bootstrap=normalizeMobile(this.config.get('BOOTSTRAP_ADMIN_MOBILE',''));const [existing]:any=await this.db.query(`SELECT id,name,mobile_number AS mobile,status FROM users WHERE normalized_mobile=:mobile LIMIT 1`,{replacements:{mobile}});let userId:string,name:string;if(existing.length){if(String(existing[0].status).toUpperCase()==='DELETED')throw new UnauthorizedException('User account is deleted');userId=existing[0].id;name=existing[0].name;}else{const admin=!!bootstrap&&mobile===bootstrap;const [created]:any=await this.db.query(`INSERT INTO users(id,mobile_number,normalized_mobile,name,status,preferred_language,timezone,last_login_at,created_at,updated_at) VALUES(gen_random_uuid(),:mobile,:mobile,:name,'ACTIVE','en','Asia/Kolkata',NOW(),NOW(),NOW()) RETURNING id,name`,{replacements:{mobile,name:admin?'System Administrator':`User ${mobile}`}});userId=created[0].id;name=created[0].name;}await this.db.query(`UPDATE users SET last_login_at=NOW(),updated_at=NOW() WHERE id=:id`,{replacements:{id:userId}});const[roleRows]:any=await this.db.query(`SELECT role FROM user_roles WHERE user_id=:id ORDER BY role`,{replacements:{id:userId}});let roles=roleRows.map((r:any)=>r.role);if(!roles.length){const role=bootstrap&&mobile===bootstrap?'ADMIN':'MEMBER';await this.db.query(`INSERT INTO user_roles(id,user_id,role,created_at,updated_at) VALUES(gen_random_uuid(),:user,:role,NOW(),NOW()) ON CONFLICT(user_id,role) DO NOTHING`,{replacements:{user:userId,role}});roles=[role];}const accessToken=this.access(userId,mobile,roles),refresh=await this.createRefresh(userId,req);return{success:true,data:{accessToken,refreshToken:refresh.token,refreshExpiresAt:refresh.expiresAt,user:{id:userId,name,mobile,roles}}};}
 @Post('refresh') async refresh(@Body()d:RefreshDto,@Req()req:any){const h=hash(d.refreshToken);return this.db.transaction(async t=>{const[rows]:any=await this.db.query(`SELECT rs.*,u.mobile_number,u.name FROM refresh_sessions rs JOIN users u ON u.id=rs.user_id WHERE rs.token_hash=:hash AND rs.revoked_at IS NULL AND rs.expires_at>NOW() LIMIT 1 FOR UPDATE`,{replacements:{hash:h},transaction:t});if(!rows.length)throw new UnauthorizedException('Refresh token is invalid or expired');const s=rows[0];const[roles]:any=await this.db.query(`SELECT role FROM user_roles WHERE user_id=:id ORDER BY role`,{replacements:{id:s.user_id},transaction:t});await this.db.query(`UPDATE refresh_sessions SET revoked_at=NOW(),updated_at=NOW() WHERE id=:id`,{replacements:{id:s.id},transaction:t});const next=await this.createRefresh(s.user_id,req,t);await this.db.query(`UPDATE refresh_sessions SET rotated_to_id=:next,updated_at=NOW() WHERE id=:id`,{replacements:{id:s.id,next:next.id},transaction:t});return{success:true,data:{accessToken:this.access(s.user_id,s.mobile_number,roles.map((r:any)=>r.role)),refreshToken:next.token,refreshExpiresAt:next.expiresAt,user:{id:s.user_id,name:s.name,mobile:s.mobile_number,roles:roles.map((r:any)=>r.role)}}};});}
 @Post('logout') @ApiBearerAuth('access-token') async logout(@Body()d:RefreshDto){await this.db.query(`UPDATE refresh_sessions SET revoked_at=NOW(),updated_at=NOW() WHERE token_hash=:hash AND revoked_at IS NULL`,{replacements:{hash:hash(d.refreshToken)}});return{success:true};}
}
@Global() @Module({imports:[ConfigModule,DatabaseModule,JwtModule.registerAsync({imports:[ConfigModule],inject:[ConfigService],useFactory:(c:ConfigService)=>({secret:c.getOrThrow('JWT_ACCESS_SECRET'),signOptions:{expiresIn:c.get('JWT_ACCESS_EXPIRES','15m')}})})],controllers:[AuthController],providers:[JwtAuthGuard],exports:[JwtAuthGuard,JwtModule]})
export class AuthModule {}
